{{/*
Copyright (c) spectryn
SPDX-License-Identifier: MIT
*/}}

{{- if and .Values.operator.enabled .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spectryn.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectryn.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "spectryn.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: operator
---
{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spectryn.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectryn.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "spectryn.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
{{- end }}
